# Generated by Django 5.1 on 2024-11-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinments',
            new_name='Appoinment',
        ),
    ]
